#!/usr/bin/env python3
import json
from glob import glob
from os.path import join
from os import listdir
from pathlib import Path
from snakemake.workflow import workflow as wf_api
from snakemake.utils import R
from scripts.common import (
    allocated,
    provided, 
    references,
    str_bool,
    get_sid
)


# project configuration options
samples                         = config["samples"]
genome                          = config['options']['genome_alias']
genome_files                    = config["references"][genome]
ref2bit                         = 'ref2bit' in genome_files
intervals                       = 'intervals' in genome_files
chrom_sizes                     = 'chrom_sizes' in genome_files
tss                             = 'tss' in genome_files
tss_interval                    = 'tss_interval' in genome_files
split_interval                  = int(config['options']['interval'])
max_fragment_len                = int(config['options']['max'])
min_fragment_len                = int(config['options']['min'])
bin_size                        = int(config['options']['bin_size'])

# directories
data_dir                         = config["project"]["datapath"]
all_input_files                  = config['options']['input']
output_dir                       = config['options']['output']
bin_dir                          = config['binpath']
bam_dir                          = os.path.join(output_dir, 'bams')
coverage_dir                     = os.path.join(output_dir, 'coverage')
fragment_length_dir              = os.path.join(output_dir, 'frag_length_bins')
fragment_length_int_dir          = os.path.join(output_dir, 'frag_length_intervals')
end_motifs_dir                   = os.path.join(output_dir, 'end_motifs')
interval_end_motifs_dir          = os.path.join(output_dir, 'interval_end_motifs')
mds_dir                          = os.path.join(output_dir, 'mds')
delfi_dir                        = os.path.join(output_dir, 'delfi')
wps_dir                          = os.path.join(output_dir, 'wps')
adjust_wps_dir                   = os.path.join(output_dir, 'adjust_wps')
cleavage_profile_dir             = os.path.join(output_dir, 'cleavage_profile')

# Define outputs
all_outputs = []

# Bam starting point (convert any sam/cram)
# Fragment length bins
all_outputs.extend(
    expand(os.path.join(bam_dir, "{sample}.sorted.bam"), sample=samples)
)

all_outputs.extend(
    expand(
        os.path.join(fragment_length_dir, "{sample}_frag_bin{bin_size}.tsv"), 
        sample=samples, 
        bin_size=[bin_size]
    )
)

if split_interval:
    all_outputs.extend(
        expand(
            os.path.join(fragment_length_int_dir, "{sample}_frag_interval.bed"),
            sample=samples
        )
    )

if ref2bit:
    all_outputs.extend(expand(os.path.join(end_motifs_dir, "{sample}_endmotif.tsv"), sample=samples))
    all_outputs.extend(expand(os.path.join(mds_dir, "{sample}_mds.tsv"), sample=samples))
    if intervals:
        all_outputs.extend(expand(os.path.join(interval_end_motifs_dir, "{sample}_endmotif_interval.tsv"), sample=samples))
        if chrom_sizes:
            all_outputs.extend(expand(os.path.join(delfi_dir, "{sample}_delfi.bed"), sample=samples))

if tss:
    all_outputs.extend(expand(os.path.join(wps_dir, "{sample}_wps_out_tss.bw"), sample=samples))
    if tss_interval:
        all_outputs.extend(expand(os.path.join(wps_dir, "{sample}_wps_out_tss_aggr.wig"), sample=samples))
    if chrom_sizes and tss_interval:
        all_outputs.extend(expand(os.path.join(adjust_wps_dir, "{sample}_wps_out_tss_adjusted.bw"), sample=samples))
        all_outputs.extend(expand(os.path.join(cleavage_profile_dir, "{sample}_cleavage_profile_tss.bw"), sample=samples))
        all_outputs.extend(expand(os.path.join(adjust_wps_dir, "{sample}_wps_out_tss_adj_aggr.wig"), sample=samples))
        all_outputs.extend(expand(os.path.join(cleavage_profile_dir, "{sample}_cleavage_profile_aggr.wig"), sample=samples))

rule all:
    input:
        all_outputs


# Import rules 
include: join("rules", "common.smk")
include: join("rules", "hooks.smk")
