# Project Information
site_name: fragmentomics
site_author: Skyler Kuhn
site_description: >-
  An awesome OpenOmics fragmentomics pipeline

# Repository
repo_name: OpenOmics/fragmentomics
repo_url: https://github.com/OpenOmics/fragmentomics
edit_uri: https://github.com/OpenOmics/fragmentomics/edit/main/docs/

# Extra
extra_css:
  - css/extra.css

# Copyright
copyright: Copyright &copy; 2026 OpenOmics

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate 
  palette:
    # Palette toggle for light mode 
    - scheme: default
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  logo: assets/icons/doc-book.svg
  favicon: assets/favicon/favicon.ico

# Plugins
plugins:
  - search
  - git-revision-date
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/solid/users
      link: https://idss-bioinformatics.nih.gov/
    - icon: fontawesome/brands/github
      link: https://github.com/OpenOmics
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/skchronicles

# Extensions
markdown_extensions:
  - markdown.extensions.md_in_html
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Tree
nav:
  - About: index.md
  - Commands: 
    - fragmentomics run: usage/run.md
    - fragmentomics unlock: usage/unlock.md
    - fragmentomics install: usage/install.md
    - fragmentomics cache: usage/cache.md
  - Pipeline:
    - Overview: pipeline/overview.md
    - FastQ alignment: pipeline/fastq-alignment.md
    - BAM normalization: pipeline/bam-normalization.md
    - Reference contig filter: pipeline/contig-filter.md
    - Reference files: pipeline/references.md
    - Quality control: pipeline/quality-control.md
  - Analyses:
    - Overview: analyses/index.md
    - coverage: analyses/coverage.md
    - frag-length-bins: analyses/frag-length-bins.md
    - frag-length-intervals: analyses/frag-length-intervals.md
    - end-motifs: analyses/end-motifs.md
    - interval-end-motifs: analyses/interval-end-motifs.md
    - mds: analyses/mds.md
    - delfi: analyses/delfi.md
    - wps: analyses/wps.md
    - adjust-wps: analyses/adjust-wps.md
    - cleavage-profile: analyses/cleavage-profile.md
    - agg-bw: analyses/agg-bw.md
  - FAQ:
    - General Questions: faq/questions.md
  - License: license.md
